from html import escape as e

options=[
 ('01 / BUSINESS WEBSITE','Make your business easy to understand.','For local businesses, consultants, shops and service providers.','web-development',['Home, about, service and contact pages agreed to your scope','Mobile-friendly design with call and WhatsApp enquiries','Your business information, real proof and a clear next step']),
 ('02 / WORDPRESS & COMMERCE','A website you can keep updating.','For businesses that publish content or manage products.','wordpress-development',['Editable pages and an agreed WordPress setup','WooCommerce catalog and checkout when required','Editing guidance and a plan for updates and backups']),
 ('03 / REDESIGN & PERFORMANCE','Give your existing website a better next chapter.','For sites that feel dated, confusing or difficult to use on phones.','website-redesign',['Review of important pages and the enquiry journey','Improved content, layout and mobile usability','URL, SEO and performance checks within the agreed scope'])
]

def offers():
 return '<section id="website-options"><div class="wrap"><div class="section-head"><div><span class="eyebrow">WEBSITES FOR CLIENTS / CHOOSE YOUR STARTING POINT</span><h2>What can I build<br>for your business?</h2></div><p>A new website, an editable store or a better version of what you already have. Each project starts with your audience and a written scope.</p></div><div class="grid">'+''.join('<article class="card"><span class="num">'+e(label)+'</span><h3>'+e(title)+'</h3><p>'+e(who)+'</p><ul>'+''.join('<li>'+e(x)+'</li>' for x in items)+'</ul><p><a href="/services/'+slug+'/">Explore this service ↗</a></p><a class="button outline" href="/hire-web-developer/#quote-form">Request a quote</a></article>' for label,title,who,slug,items in options)+'</div><p class="small" style="margin-top:24px">Need a focused campaign landing page or an interactive web tool? <a href="/services/landing-pages/">Explore landing pages</a> or <a href="/contact/">tell me about the workflow</a>.</p></div></section>'

def reassurance():
 return '''<section><div class="wrap split"><div><span class="eyebrow">YOUR PROJECT / A CLEAR AGREEMENT</span><h2>Know what you are paying for.</h2><p class="lead">I design and develop websites for clients. Before work begins, we agree the pages, features, content responsibilities, review rounds and delivery milestones.</p><p>You work directly with Nitesh Patel, the developer building your website. My professional background includes WordPress development at MBG Cards India Pvt. Ltd.</p><a class="button" href="/hire-web-developer/">Hire me for your website ↗</a></div><div class="timeline"><article><span class="meta">01 / DISCUSS</span><h3>Your goal becomes a brief.</h3><p>Share your business, existing website and the action customers should take. We identify the pages and functionality you need.</p></article><article><span class="meta">02 / AGREE</span><h3>Scope, quote and milestones.</h3><p>We define deliverables and review points. Hosting, domains, paid tools and ongoing maintenance are listed separately where applicable.</p></article><article><span class="meta">03 / BUILD & REVIEW</span><h3>See the work before launch.</h3><p>Review the design and working website, then check the content and enquiry flow before it goes live.</p></article><article><span class="meta">04 / HANDOVER</span><h3>Understand what comes next.</h3><p>Agree account ownership, code or CMS access, editing guidance and the support scope. Any maintenance work is defined separately.</p></article></div></div></section>'''

def business_proof():
 examples=[('shri-dadaji','A local shop with a direct enquiry route','Product categories, shop information and contact actions in a bilingual agricultural storefront.'),('happyhealing','Products with a clear shopping context','A handloom saree storefront with product presentation and a route into the collection.'),('ak-goud-properties','A property business with a clear enquiry path','AK Goud Properties presents property services, Hyderabad locations and contact options for prospective buyers.')]
 return '<section><div class="wrap"><span class="eyebrow">BUSINESS WEBSITE EXAMPLES</span><h2>See what a business website can do.</h2><p class="lead">Explore the live work and its interface. These examples show the kind of website I can discuss with you.</p><div class="grid">'+''.join(f'<a class="card" href="/projects/{slug}/"><img src="/assets/{slug}.webp" width="1200" height="800" loading="lazy" decoding="async" alt="{e(title)} website example" style="width:100%;height:auto;border-radius:8px"><h3>{e(title)}</h3><p>{e(desc)}</p><span class="link">Explore the project ↗</span></a>' for slug,title,desc in examples)+'</div></div></section>'

def buyer_questions():
 items=[('How much will my website cost?','The quote depends on pages, features, content, integrations and editing needs. Send a brief for an estimate. The proposal should distinguish the build fee from domain, hosting, subscriptions and ongoing maintenance.'),('How long does a project take?','We agree a delivery plan after reviewing the scope and content readiness. Integrations, feedback and approvals affect the timeline, so milestones are defined for your project.'),('Can I update the website myself?','Yes, where an editable WordPress or CMS setup is included. We agree which content you need to edit and include that requirement in the platform choice and handover.'),('Can you improve my current website?','Yes. Share the URL and what is not working for your business. I can review the content, mobile experience, enquiry route and technical issues, then propose a focused redesign or improvement scope.'),('Will my website rank first on Google?','No developer can guarantee a search position. I can include sound technical SEO, useful page structure and relevant content within scope. Visibility also depends on competition, content quality and the wider business presence.'),('What do you need from me?','Your business description, audience, page or feature list, logo and content if ready, examples you like, and any existing website. Tell me your target launch window and budget range if you have one.')]
 return '<section><div class="wrap"><span class="eyebrow">BEFORE YOU HIRE / PRACTICAL ANSWERS</span><h2>Let’s make the decision easier.</h2><div class="faq-list">'+''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in items)+'</div></div></section>'

def hire_page(form):
 return '''<div class="wrap page-intro"><span class="eyebrow">HIRE NITESH PATEL / JABALPUR & REMOTE</span><h1>A website for your business.<br>A developer you can speak to.</h1><p class="lead">Hire me to design and build a responsive business website, WordPress site, store or focused landing page. Start with your goals; we will agree a practical scope before building.</p><div class="actions"><a class="button" href="#quote-form">Request a website quote ↗</a><a class="button outline" href="/projects/">See the work</a></div></div>'''+offers()+business_proof()+reassurance()+buyer_questions()+f'''<section id="quote-form"><div class="wrap split"><div><span class="eyebrow">YOUR NEXT WEBSITE / START HERE</span><h2>Tell me about your business.</h2><p class="lead">Use this form to prepare a WhatsApp enquiry. Include the pages and features you need, your existing site if any, and your target launch window.</p><p>I’ll review your requirements so we can discuss the platform, scope and estimate. You can review the message in WhatsApp before sending.</p><p><a href="tel:+917974823298">+91 79748 23298</a><br><a href="mailto:niteshpatel7479@gmail.com">niteshpatel7479@gmail.com</a></p></div>{form}</div></section>'''
